import type { Metadata } from "next";
import "./globals.css";
import Navigation from "./components/navigation";
import { campton } from "./fonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${campton.variable} antialiased`}>
        <Navigation />
        {children}
        <div className="flex flex-col items-center  mt-24 mb-10">
          <div className="text-center text-xl  leading-7 text-black">
            © KATJA KURZ LEVRING 2024 ALL RIGHTS RESERVED. <br />
            ALL COMPANY LOGOS BELONG TO THEIR RESPECTIVE OWNERS.
          </div>
          <div className="mt-3">
            <a href="https://makl.dk" className="hover:underline">
              Developed by makl 🧑🏼‍💻
            </a>
          </div>
        </div>
      </body>
    </html>
  );
}
